Traceback (most recent call last):
  File "/root/runs/caso_laboratorio/fenicsx/fenicsx_main.py", line 22, in <module>
    alpha = parameters['alpha']
KeyError: 'alpha'
